### ISSUE TITLE
Tracking issue for Enclave data pooling support

### ISSUE THREAD

**Issue by longtomjr** [ntls-io/nautilus-trusted-compute#10]
## Tasks
- [ ] Add support for verifying authorizations for data pool requests
- [ ] Add a special case execution that appends one data set to a data pool
- [ ] Add data package creation after the append operation that creates a new data package for the data pool
