### ISSUE TITLE
Tracking issue for Milestone 1: Data sealing, Wasm execution and DRTs

### ISSUE THREAD

**Issue by PiDelport** [ntls-io/nautilus-trusted-compute#2]
The main goal of this milestone is to lay out initial versions of each of the following components:

- [ ] Data package library - #4
- [ ] Vault CLI - #5
- [ ] TEE server - #7
- [ ] Sealed messaging library
- [ ] Authorisation library - #6
- [ ] Wasm runtime library - https://github.com/ntls-io/wasm-exec-sgx

Follow-up tasks:

- [ ] Integrate [sgx-dcap-attestation-rust](https://github.com/ntls-io/sgx-dcap-attestation-rust) library with the TEE container

(Context: [Roadmap](https://docs.google.com/document/d/140iY16L5x2gtqIpD900I2XOk-xNIO0YAL_WhnCUYmEg/edit#heading=h.wmsadkntgaj0))
