### ISSUE TITLE
Tracking issue for the Vault CLI

### ISSUE THREAD

**Issue by longtomjr** [ntls-io/nautilus-trusted-compute#5]
## Tasks
- [ ] Add data package creation #1
- [ ] Add data package upload
- [ ] Add DRT issuance

## Implementation
- Use data package library to seal data
- Use authorization library to issue authorizations
