### ISSUE TITLE
Tracking issue for the Authorization Library

### ISSUE THREAD

**Issue by longtomjr** [ntls-io/nautilus-trusted-compute#6]
## Tasks
- [ ] Integrate with Algorand to allow ASA creation
  - probably use https://lib.rs/crates/algonaut
- [ ] Add code to check and compile information about a specific transaction for an ASA. (Redemption transaction)
- [ ] Add signing API that will be used by oracle nodes
