### ISSUE TITLE
Tracking issue for the TEE container and Enclave

### ISSUE THREAD

**Issue by longtomjr** [ntls-io/nautilus-trusted-compute#7]
## Tasks - Container
- [ ] Add endpoint for requesting attestation
- [ ] Add endpoint for enclave operations that receive sealed enclave communication

##  Tasks - Enclave
- [ ] Add execution environment using https://github.com/ntls-io/wasm-exec-sgx
- [ ] Add authorization verification functionality
- [ ] Add execution request functionality
- [ ] Add ecall interface for receiving enclave communication
  - Use a similar method as the wallet

## Implementation
- Create a standalone library to handle enclave communication using messagepack (probably separate repository)
  - Look at the wallet code for this and pull out the relevant pieces into a communication library.
